// Code generated by protoc-gen-go.
// source: sync_files.proto
// DO NOT EDIT!

/*
Package sync_proto is a generated protocol buffer package.

It is generated from these files:
	sync_files.proto

It has these top-level messages:
	SyncFileInfo
	SyncFileInfoResp
	SyncFileData
	SyncFileComplete
*/
package sync_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SYNC int32

const (
	SYNC_Msg_SyncFileInfo     SYNC = 1
	SYNC_Msg_SyncFileInfoResp SYNC = 2
	SYNC_Msg_SyncFileData     SYNC = 3
	SYNC_Msg_SyncFileComplete SYNC = 4
)

var SYNC_name = map[int32]string{
	1: "Msg_SyncFileInfo",
	2: "Msg_SyncFileInfoResp",
	3: "Msg_SyncFileData",
	4: "Msg_SyncFileComplete",
}
var SYNC_value = map[string]int32{
	"Msg_SyncFileInfo":     1,
	"Msg_SyncFileInfoResp": 2,
	"Msg_SyncFileData":     3,
	"Msg_SyncFileComplete": 4,
}

func (x SYNC) Enum() *SYNC {
	p := new(SYNC)
	*p = x
	return p
}
func (x SYNC) String() string {
	return proto.EnumName(SYNC_name, int32(x))
}
func (x *SYNC) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SYNC_value, data, "SYNC")
	if err != nil {
		return err
	}
	*x = SYNC(value)
	return nil
}
func (SYNC) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// client -> Server Type : 0001
type SyncFileInfo struct {
	FileName         *string `protobuf:"bytes,1,req,name=file_name" json:"file_name,omitempty"`
	HashCode         *uint64 `protobuf:"varint,2,req,name=hash_code" json:"hash_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncFileInfo) Reset()                    { *m = SyncFileInfo{} }
func (m *SyncFileInfo) String() string            { return proto.CompactTextString(m) }
func (*SyncFileInfo) ProtoMessage()               {}
func (*SyncFileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SyncFileInfo) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *SyncFileInfo) GetHashCode() uint64 {
	if m != nil && m.HashCode != nil {
		return *m.HashCode
	}
	return 0
}

// server -> client Type : 8002
type SyncFileInfoResp struct {
	FileName         *string `protobuf:"bytes,1,req,name=file_name" json:"file_name,omitempty"`
	NeedSync         *bool   `protobuf:"varint,2,req,name=need_sync" json:"need_sync,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncFileInfoResp) Reset()                    { *m = SyncFileInfoResp{} }
func (m *SyncFileInfoResp) String() string            { return proto.CompactTextString(m) }
func (*SyncFileInfoResp) ProtoMessage()               {}
func (*SyncFileInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SyncFileInfoResp) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *SyncFileInfoResp) GetNeedSync() bool {
	if m != nil && m.NeedSync != nil {
		return *m.NeedSync
	}
	return false
}

// client -> client Type : 0002
type SyncFileData struct {
	FileName         *string `protobuf:"bytes,1,req,name=file_name" json:"file_name,omitempty"`
	FileMode         *uint32 `protobuf:"varint,2,opt,name=file_mode" json:"file_mode,omitempty"`
	TotalPacks       *uint32 `protobuf:"varint,3,req,name=total_packs" json:"total_packs,omitempty"`
	CurrentPacks     *uint32 `protobuf:"varint,4,req,name=current_packs" json:"current_packs,omitempty"`
	Data             []byte  `protobuf:"bytes,5,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncFileData) Reset()                    { *m = SyncFileData{} }
func (m *SyncFileData) String() string            { return proto.CompactTextString(m) }
func (*SyncFileData) ProtoMessage()               {}
func (*SyncFileData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SyncFileData) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *SyncFileData) GetFileMode() uint32 {
	if m != nil && m.FileMode != nil {
		return *m.FileMode
	}
	return 0
}

func (m *SyncFileData) GetTotalPacks() uint32 {
	if m != nil && m.TotalPacks != nil {
		return *m.TotalPacks
	}
	return 0
}

func (m *SyncFileData) GetCurrentPacks() uint32 {
	if m != nil && m.CurrentPacks != nil {
		return *m.CurrentPacks
	}
	return 0
}

func (m *SyncFileData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 告知客户端，文件已经发送完毕了
type SyncFileComplete struct {
	FileName         *string `protobuf:"bytes,1,req,name=file_name" json:"file_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncFileComplete) Reset()                    { *m = SyncFileComplete{} }
func (m *SyncFileComplete) String() string            { return proto.CompactTextString(m) }
func (*SyncFileComplete) ProtoMessage()               {}
func (*SyncFileComplete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SyncFileComplete) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func init() {
	proto.RegisterType((*SyncFileInfo)(nil), "sync_proto.SyncFileInfo")
	proto.RegisterType((*SyncFileInfoResp)(nil), "sync_proto.SyncFileInfoResp")
	proto.RegisterType((*SyncFileData)(nil), "sync_proto.SyncFileData")
	proto.RegisterType((*SyncFileComplete)(nil), "sync_proto.SyncFileComplete")
	proto.RegisterEnum("sync_proto.SYNC", SYNC_name, SYNC_value)
}

func init() { proto.RegisterFile("sync_files.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0x69, 0x2e, 0x82, 0xf7, 0x6c, 0x21, 0xc6, 0x13, 0x32, 0x96, 0x82, 0x10, 0x1c, 0x9c,
	0x1c, 0xdc, 0x4f, 0x04, 0x07, 0x1d, 0xbc, 0xc9, 0x29, 0x3c, 0xd2, 0x57, 0xef, 0xb0, 0x4d, 0x4a,
	0x13, 0x87, 0xfb, 0xef, 0x25, 0x51, 0xb9, 0xa3, 0x78, 0xdb, 0xe3, 0xc7, 0xf7, 0xf1, 0x7b, 0x1f,
	0x88, 0xb0, 0x77, 0xd6, 0x74, 0xbb, 0x9e, 0xc2, 0xdd, 0x38, 0xf9, 0xe8, 0x25, 0x64, 0x92, 0xef,
	0xe6, 0x1e, 0xca, 0xcd, 0xde, 0xd9, 0xa7, 0x5d, 0x4f, 0xcf, 0xae, 0xf3, 0xf2, 0x12, 0x96, 0x29,
	0x6a, 0x1c, 0x0e, 0xa4, 0x8a, 0x9a, 0xe9, 0x65, 0x42, 0x5b, 0x0c, 0x5b, 0x63, 0x7d, 0x4b, 0x8a,
	0xd5, 0x4c, 0xf3, 0xe6, 0x01, 0xc4, 0x71, 0xeb, 0x8d, 0xc2, 0x78, 0xa2, 0xe9, 0x88, 0x5a, 0x93,
	0x7c, 0xb9, 0x79, 0xde, 0xb8, 0x83, 0xef, 0x11, 0x23, 0x9e, 0x68, 0x65, 0x34, 0xfc, 0xf8, 0x0a,
	0x5d, 0xc9, 0x2b, 0xb8, 0x88, 0x3e, 0x62, 0x6f, 0x46, 0xb4, 0x9f, 0x41, 0x2d, 0x6a, 0xa6, 0x2b,
	0x79, 0x0d, 0x95, 0xfd, 0x9a, 0x26, 0x72, 0xf1, 0x17, 0xf3, 0x8c, 0x4b, 0xe0, 0x2d, 0x46, 0x54,
	0x67, 0x35, 0xd3, 0x65, 0x73, 0x73, 0xf8, 0x74, 0xed, 0x87, 0xb1, 0xa7, 0x48, 0xff, 0x38, 0x6f,
	0x3b, 0xe0, 0x9b, 0xf7, 0xd7, 0xb5, 0x5c, 0x81, 0x78, 0x09, 0x1f, 0xe6, 0x78, 0x9c, 0x28, 0xa4,
	0x82, 0xd5, 0x9c, 0xa6, 0xc9, 0x82, 0xcd, 0xf3, 0x69, 0x92, 0x58, 0xcc, 0xf3, 0x7f, 0x62, 0xc1,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x75, 0x93, 0xa8, 0x1b, 0x8d, 0x01, 0x00, 0x00,
}
